# Generated by Django 5.1.4 on 2026-07-22 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the presentation.', primary_key=True, serialize=False)),
                ('original_text', models.TextField(help_text='The original technical content submitted for slide generation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the presentation was generated.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to this record.')),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_order', models.IntegerField(help_text='Zero-based order of the slide within the presentation.')),
                ('title', models.CharField(help_text='Concise slide title.', max_length=255)),
                ('bullet_points', models.JSONField(default=list, help_text='JSON array of bullet-point strings.')),
                ('theme_variant', models.CharField(help_text='Visual theme: "warm", "bold", or "clean".', max_length=10)),
                ('presentation', models.ForeignKey(help_text='The presentation this slide belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='storyteller.presentation')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['slide_order'],
                'unique_together': {('presentation', 'slide_order')},
            },
        ),
    ]
