# Generated by Django 5.1.4 on 2026-07-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyteller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='diagram_code',
            field=models.TextField(blank=True, default='', help_text='Optional Mermaid.js diagram syntax for visual rendering.'),
        ),
    ]
