"""
storyteller/views.py

HTTP layer for the Fafanua slide generation API.

This module contains only HTTP-level concerns: request parsing, input
validation, error translation, and response serialisation. All business
logic and external-API communication lives in services.py.
"""

import logging

from io import BytesIO

from django.db import transaction
from django.http import HttpResponse
from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema
from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer
from rest_framework import status
from rest_framework.generics import get_object_or_404
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Presentation, Slide
from .pptx_service import PPTXGenerator
from .serializers import PresentationSerializer, SlideSerializer
from .services import WatsonxService

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# OpenAPI schema definitions (reused across decorator and response docs)
# ---------------------------------------------------------------------------

_slide_schema = openapi.Schema(
    type=openapi.TYPE_OBJECT,
    description="A single presentation slide generated by the Granite model.",
    required=["title", "bullet_points", "theme_variant"],
    properties={
        "title": openapi.Schema(
            type=openapi.TYPE_STRING,
            description="Concise, punchy slide title.",
            example="Decoupled Architecture Overview",
        ),
        "bullet_points": openapi.Schema(
            type=openapi.TYPE_ARRAY,
            description="3–5 audience-friendly bullet points.",
            items=openapi.Schema(
                type=openapi.TYPE_STRING,
                example="The React frontend communicates with Django via a REST API.",
            ),
        ),
        "theme_variant": openapi.Schema(
            type=openapi.TYPE_STRING,
            description='Visual theme. Must be one of: "warm", "bold", or "clean".',
            enum=["warm", "bold", "clean"],
            example="bold",
        ),
    },
)

_request_schema = openapi.Schema(
    type=openapi.TYPE_OBJECT,
    required=["technical_content"],
    properties={
        "technical_content": openapi.Schema(
            type=openapi.TYPE_STRING,
            description=(
                "Dense technical text to transform — architecture docs, "
                "code snippets, system logs, or API specifications."
            ),
            example="Our system uses a React frontend with a Django REST API backend...",
        )
    },
)

_presentation_response_schema = openapi.Schema(
    type=openapi.TYPE_OBJECT,
    description="A persisted presentation with nested slides.",
    properties={
        "id": openapi.Schema(
            type=openapi.TYPE_STRING,
            format="uuid",
            description="Unique presentation identifier.",
        ),
        "original_text": openapi.Schema(
            type=openapi.TYPE_STRING,
            description="The original technical content submitted.",
        ),
        "slides": openapi.Schema(
            type=openapi.TYPE_ARRAY,
            items=_slide_schema,
            description="Ordered list of generated slides.",
        ),
        "created_at": openapi.Schema(
            type=openapi.TYPE_STRING,
            format="date-time",
            description="ISO-8601 creation timestamp.",
        ),
        "updated_at": openapi.Schema(
            type=openapi.TYPE_STRING,
            format="date-time",
            description="ISO-8601 last-updated timestamp.",
        ),
    },
)

_refine_request_schema = openapi.Schema(
    type=openapi.TYPE_OBJECT,
    required=["instruction"],
    properties={
        "instruction": openapi.Schema(
            type=openapi.TYPE_STRING,
            description=(
                "Natural-language feedback describing how the slide should be "
                "rewritten (e.g. 'Make this less technical', 'Add a point about "
                "security', 'Change the theme to bold')."
            ),
            example="Make the bullet points shorter and more punchy.",
        )
    },
)


class GeneratePresentationView(APIView):
    """POST /api/generate/ — converts technical text into a JSON slide deck.

    Accepts a JSON body containing ``technical_content``, delegates the heavy
    lifting to :class:`~storyteller.services.WatsonxService`, persists the
    result as a :class:`~storyteller.models.Presentation` with linked
    :class:`~storyteller.models.Slide` records, and returns the serialised
    presentation.

    HTTP Methods:
        POST

    Request Body (JSON)::

        {
            "technical_content": "<dense technical text, code, or architecture docs>"
        }

    Successful Response — 200 OK::

        {
            "id": "<uuid>",
            "original_text": "...",
            "slides": [ { "title": "...", ... }, ... ],
            "created_at": "...",
            "updated_at": "..."
        }

    Error Responses:
        - **400 Bad Request** — ``technical_content`` is missing or blank.
        - **502 Bad Gateway** — watsonx.ai API returned an upstream error.
        - **500 Internal Server Error** — Unexpected failure or unparseable model response.
    """

    @swagger_auto_schema(
        operation_id="generate_presentation",
        operation_summary="Generate a slide deck from technical content",
        operation_description=(
            "Accepts dense technical text and returns a persisted presentation "
            "object containing a structured JSON array of slides. Each slide is "
            "generated by the IBM Granite model (`ibm/granite-3-3-8b-instruct`) "
            "via a zero-shot prompt and contains a title, bullet points, and a "
            "theme variant. The presentation and its slides are saved to the "
            "database for later retrieval via the history endpoints."
        ),
        request_body=_request_schema,
        responses={
            200: openapi.Response(
                description="Presentation generated and persisted successfully.",
                schema=_presentation_response_schema,
            ),
            400: openapi.Response(
                description="Bad Request — `technical_content` is missing or blank.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(
                            type=openapi.TYPE_STRING,
                            example="'technical_content' is required and must not be blank.",
                        )
                    },
                ),
            ),
            502: openapi.Response(
                description="Bad Gateway — IBM watsonx.ai API returned an upstream error.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(type=openapi.TYPE_STRING),
                        "upstream_error": openapi.Schema(type=openapi.TYPE_STRING),
                    },
                ),
            ),
            500: openapi.Response(
                description="Internal Server Error — server misconfiguration or unparseable model output.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(type=openapi.TYPE_STRING),
                        "parse_error": openapi.Schema(type=openapi.TYPE_STRING),
                    },
                ),
            ),
        },
        tags=["Slide Generation"],
    )
    def post(self, request: Request, *args, **kwargs) -> Response:
        """Handle POST requests by generating a slide deck via IBM watsonx.ai.

        Args:
            request: The DRF request object. Expects a JSON body with the key
                ``technical_content``.
            *args: Additional positional arguments (passed through, unused).
            **kwargs: Additional keyword arguments (passed through, unused).

        Returns:
            A :class:`rest_framework.response.Response` containing either:

            - A serialised ``Presentation`` dict on success (HTTP 200).
            - An error dict with a ``detail`` key on failure (HTTP 400/500/502).
        """
        # ------------------------------------------------------------------ #
        # 1. Input validation
        # ------------------------------------------------------------------ #
        technical_content: str = request.data.get("technical_content", "").strip()

        if not technical_content:
            return Response(
                {
                    "detail": (
                        "'technical_content' is required and must not be blank. "
                        "Paste your technical text, code snippet, or architecture "
                        "notes into this field."
                    )
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

        # ------------------------------------------------------------------ #
        # 2. Delegate to the service layer
        # ------------------------------------------------------------------ #
        try:
            service = WatsonxService()
            slides = service.generate_slides(technical_content)

        except EnvironmentError as exc:
            # Misconfigured server — watsonx credentials not set in .env
            logger.error("WatsonxService configuration error: %s", exc)
            return Response(
                {
                    "error": "Failed to generate presentation",
                    "detail": f"Server configuration error: {exc}",
                    "details": str(exc),
                },
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        except RuntimeError as exc:
            # watsonx.ai upstream API failure (network, auth, quota, etc.)
            logger.error("watsonx.ai upstream error: %s", exc)
            return Response(
                {
                    "error": "Failed to generate presentation",
                    "detail": "The AI service returned an error. Please try again in a moment.",
                    "details": str(exc),
                    "upstream_error": str(exc),
                },
                status=status.HTTP_502_BAD_GATEWAY,
            )

        except ValueError as exc:
            # Model returned non-parseable output
            logger.error("JSON parse error from model response: %s", exc)
            return Response(
                {
                    "error": "Failed to generate presentation",
                    "detail": "The AI model returned an unexpected response format.",
                    "details": str(exc),
                    "parse_error": str(exc),
                },
                status=status.HTTP_502_BAD_GATEWAY,
            )

        except Exception as exc:
            # Fallback for any unhandled exception to prevent HTML 500 error page
            logger.exception("Unexpected error during presentation generation: %s", exc)
            return Response(
                {
                    "error": "Failed to generate presentation",
                    "detail": "An unexpected error occurred during presentation generation.",
                    "details": str(exc),
                },
                status=status.HTTP_502_BAD_GATEWAY,
            )

        # ------------------------------------------------------------------ #
        # 3. Persist the presentation and slides
        # ------------------------------------------------------------------ #
        try:
            with transaction.atomic():
                presentation = Presentation.objects.create(
                    original_text=technical_content,
                )

                slide_objects = [
                    Slide(
                        presentation=presentation,
                        slide_order=idx,
                        title=slide_data.get("title", ""),
                        bullet_points=slide_data.get("bullet_points", []),
                        theme_variant=slide_data.get("theme_variant", "clean"),
                        diagram_code=slide_data.get("diagram_code", ""),
                    )
                    for idx, slide_data in enumerate(slides)
                ]
                Slide.objects.bulk_create(slide_objects)

        except Exception as exc:
            logger.exception(
                "Failed to persist presentation to database: %s", exc
            )
            # Even though DB write failed, the slides were generated
            # successfully. Return them with an error flag so the frontend
            # can still display the content.
            return Response(
                {
                    "detail": (
                        "Slides were generated successfully, but could not be "
                        "saved to the database. They will not appear in your "
                        "history."
                    ),
                    "slides": slides,
                },
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        # ------------------------------------------------------------------ #
        # 4. Return serialised presentation
        # ------------------------------------------------------------------ #
        serializer = PresentationSerializer(presentation)
        logger.info(
            "Successfully generated and persisted presentation %s with %d slides.",
            presentation.id,
            len(slides),
        )
        return Response(serializer.data, status=status.HTTP_200_OK)


# ---------------------------------------------------------------------------
# History endpoints
# ---------------------------------------------------------------------------


class PresentationListView(APIView):
    """GET /api/history/ — returns all presentations ordered by newest first.

    HTTP Methods:
        GET

    Successful Response — 200 OK::

        [
            {
                "id": "<uuid>",
                "original_text": "...",
                "slides": [...],
                "created_at": "...",
                "updated_at": "..."
            },
            ...
        ]
    """

    @swagger_auto_schema(
        operation_id="list_presentations",
        operation_summary="List all generated presentations",
        operation_description=(
            "Returns a chronologically ordered list (newest first) of all "
            "persisted presentations, each including its nested slides."
        ),
        responses={
            200: openapi.Response(
                description="List of presentations retrieved successfully.",
                schema=openapi.Schema(
                    type=openapi.TYPE_ARRAY,
                    items=_presentation_response_schema,
                ),
            ),
        },
        tags=["Presentation History"],
    )
    def get(self, request: Request) -> Response:
        """Return all presentations ordered by most recent first.

        Args:
            request: The DRF request object.

        Returns:
            A list of serialised Presentation objects.
        """
        presentations = Presentation.objects.prefetch_related("slides").all()
        serializer = PresentationSerializer(presentations, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


class PresentationDetailView(APIView):
    """GET /api/history/<uuid:pk>/ — returns a single presentation by its UUID.

    HTTP Methods:
        GET

    Successful Response — 200 OK::

        {
            "id": "<uuid>",
            "original_text": "...",
            "slides": [...],
            "created_at": "...",
            "updated_at": "..."
        }

    Error Responses:
        - **404 Not Found** — No presentation with the given UUID exists.
    """

    @swagger_auto_schema(
        operation_id="retrieve_presentation",
        operation_summary="Retrieve a single presentation by UUID",
        operation_description=(
            "Returns a single presentation identified by its UUID, including "
            "all nested slides. Returns 404 if the UUID does not match any "
            "existing presentation."
        ),
        manual_parameters=[
            openapi.Parameter(
                "pk",
                openapi.IN_PATH,
                description="UUID of the presentation to retrieve.",
                type=openapi.TYPE_STRING,
                format="uuid",
                required=True,
            ),
        ],
        responses={
            200: openapi.Response(
                description="Presentation retrieved successfully.",
                schema=_presentation_response_schema,
            ),
            404: openapi.Response(
                description="Not Found — no presentation matches the given UUID.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(
                            type=openapi.TYPE_STRING,
                            example="Not found.",
                        )
                    },
                ),
            ),
        },
        tags=["Presentation History"],
    )
    def get(self, request: Request, pk) -> Response:
        """Return a single presentation by its primary key.

        Args:
            request: The DRF request object.
            pk: The UUID of the presentation to retrieve.

        Returns:
            A serialised Presentation object, or a 404 error response.
        """
        presentation = get_object_or_404(
            Presentation.objects.prefetch_related("slides"),
            pk=pk,
        )
        serializer = PresentationSerializer(presentation)
        return Response(serializer.data, status=status.HTTP_200_OK)


# ---------------------------------------------------------------------------
# Slide refinement
# ---------------------------------------------------------------------------


class SlideRefineView(APIView):
    """PATCH /api/history/<uuid>/slides/<id>/refine/ — AI-powered slide rewrite.

    Accepts a natural-language ``instruction`` and uses IBM Granite to rewrite
    a single slide. The updated content is persisted and the serialised slide
    is returned.

    HTTP Methods:
        PATCH

    Request Body (JSON)::

        {
            "instruction": "Make the bullet points shorter and more punchy."
        }

    Successful Response — 200 OK::

        {
            "id": 7,
            "slide_order": 2,
            "title": "...",
            "bullet_points": ["...", "..."],
            "theme_variant": "bold"
        }

    Error Responses:
        - **400 Bad Request** — ``instruction`` is missing or blank.
        - **404 Not Found** — Presentation or slide does not exist.
        - **502 Bad Gateway** — watsonx.ai API returned an upstream error.
        - **500 Internal Server Error** — Unexpected failure or unparseable model output.
    """

    @swagger_auto_schema(
        operation_id="refine_slide",
        operation_summary="Refine a single slide with AI feedback",
        operation_description=(
            "Sends a natural-language instruction to the IBM Granite model to "
            "rewrite a specific slide within a saved presentation. The updated "
            "slide is persisted to the database and returned. Examples of "
            "instructions: 'Make this less technical', 'Add a point about "
            "security', 'Use a bolder theme'."
        ),
        manual_parameters=[
            openapi.Parameter(
                "presentation_pk",
                openapi.IN_PATH,
                description="UUID of the parent presentation.",
                type=openapi.TYPE_STRING,
                format="uuid",
                required=True,
            ),
            openapi.Parameter(
                "slide_id",
                openapi.IN_PATH,
                description="Integer ID of the slide to refine.",
                type=openapi.TYPE_INTEGER,
                required=True,
            ),
        ],
        request_body=_refine_request_schema,
        responses={
            200: openapi.Response(
                description="Slide refined and persisted successfully.",
                schema=_slide_schema,
            ),
            400: openapi.Response(
                description="Bad Request — `instruction` is missing or blank.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(
                            type=openapi.TYPE_STRING,
                            example="'instruction' is required and must not be blank.",
                        )
                    },
                ),
            ),
            404: openapi.Response(
                description="Not Found — presentation or slide does not exist.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(
                            type=openapi.TYPE_STRING,
                            example="Not found.",
                        )
                    },
                ),
            ),
            502: openapi.Response(
                description="Bad Gateway — IBM watsonx.ai API returned an upstream error.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(type=openapi.TYPE_STRING),
                        "upstream_error": openapi.Schema(type=openapi.TYPE_STRING),
                    },
                ),
            ),
            500: openapi.Response(
                description="Internal Server Error — unparseable model output.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(type=openapi.TYPE_STRING),
                        "parse_error": openapi.Schema(type=openapi.TYPE_STRING),
                    },
                ),
            ),
        },
        tags=["Slide Refinement"],
    )
    def patch(self, request: Request, presentation_pk, slide_id) -> Response:
        """Refine a single slide using AI-powered feedback.

        Args:
            request: The DRF request object. Expects a JSON body with the key
                ``instruction``.
            presentation_pk: UUID of the parent presentation.
            slide_id: Integer primary key of the slide to refine.

        Returns:
            A :class:`rest_framework.response.Response` containing either:

            - A serialised ``Slide`` dict on success (HTTP 200).
            - An error dict with a ``detail`` key on failure (HTTP 400/404/500/502).
        """
        # ------------------------------------------------------------------ #
        # 1. Input validation
        # ------------------------------------------------------------------ #
        instruction: str = request.data.get("instruction", "").strip()

        if not instruction:
            return Response(
                {
                    "detail": (
                        "'instruction' is required and must not be blank. "
                        "Describe how you'd like this slide to be rewritten."
                    )
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

        # ------------------------------------------------------------------ #
        # 2. Look up the presentation and slide
        # ------------------------------------------------------------------ #
        presentation = get_object_or_404(Presentation, pk=presentation_pk)
        slide = get_object_or_404(
            Slide,
            pk=slide_id,
            presentation=presentation,
        )

        # Build the current slide data dict for the service layer.
        current_slide_data = {
            "title": slide.title,
            "bullet_points": slide.bullet_points,
            "theme_variant": slide.theme_variant,
            "diagram_code": slide.diagram_code,
        }

        # ------------------------------------------------------------------ #
        # 3. Delegate to the service layer
        # ------------------------------------------------------------------ #
        try:
            service = WatsonxService()
            refined = service.refine_slide(current_slide_data, instruction)

        except EnvironmentError as exc:
            logger.error("WatsonxService configuration error: %s", exc)
            return Response(
                {"detail": f"Server configuration error: {exc}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        except RuntimeError as exc:
            logger.error("watsonx.ai upstream error during refinement: %s", exc)
            return Response(
                {
                    "detail": (
                        "The AI service returned an error while refining the slide. "
                        "Please try again in a moment."
                    ),
                    "upstream_error": str(exc),
                },
                status=status.HTTP_502_BAD_GATEWAY,
            )

        except ValueError as exc:
            logger.error("JSON parse error from refinement response: %s", exc)
            return Response(
                {
                    "detail": (
                        "The AI model returned an unexpected response format "
                        "during refinement. This is likely transient — please "
                        "retry your request."
                    ),
                    "parse_error": str(exc),
                },
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        # ------------------------------------------------------------------ #
        # 4. Persist the refined slide
        # ------------------------------------------------------------------ #
        try:
            slide.title = refined.get("title", slide.title)
            slide.bullet_points = refined.get("bullet_points", slide.bullet_points)
            slide.theme_variant = refined.get("theme_variant", slide.theme_variant)
            slide.diagram_code = refined.get("diagram_code", slide.diagram_code)
            slide.save()

        except Exception as exc:
            logger.exception("Failed to persist refined slide: %s", exc)
            return Response(
                {
                    "detail": (
                        "The slide was refined successfully by the AI, but "
                        "could not be saved to the database."
                    ),
                    "refined_slide": refined,
                },
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        # ------------------------------------------------------------------ #
        # 5. Return the updated slide
        # ------------------------------------------------------------------ #
        serializer = SlideSerializer(slide)
        logger.info(
            "Successfully refined slide %d (presentation %s).",
            slide.id,
            presentation.id,
        )
        return Response(serializer.data, status=status.HTTP_200_OK)


class PresentationExportView(APIView):
    """
    Exports a presentation as a downloadable landscape PDF document.
    GET /api/history/<uuid:pk>/export/
    """

    @swagger_auto_schema(
        operation_summary="Export presentation as PDF",
        operation_description="Generates a downloadable landscape PDF of the presentation slides.",
        responses={
            200: openapi.Response(
                description="Binary PDF file stream.",
                schema=openapi.Schema(type=openapi.TYPE_FILE),
            ),
            404: "Presentation not found.",
        },
    )
    def get(self, request: Request, pk: str) -> HttpResponse:
        presentation = get_object_or_404(Presentation, pk=pk)
        slides = list(presentation.slides.all())

        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=landscape(letter),
            leftMargin=36,
            rightMargin=36,
            topMargin=36,
            bottomMargin=36,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "SlideTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#1E293B"),
            spaceAfter=14,
        )

        bullet_style = ParagraphStyle(
            "SlideBullet",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=13,
            leading=18,
            textColor=colors.HexColor("#334155"),
            spaceAfter=8,
        )

        badge_style = ParagraphStyle(
            "SlideBadge",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=12,
            textColor=colors.HexColor("#64748B"),
            spaceAfter=8,
        )

        story = []

        for index, slide in enumerate(slides):
            theme_name = slide.theme_variant.upper() if slide.theme_variant else "CLEAN"
            story.append(
                Paragraph(
                    f"SLIDE {index + 1} &nbsp;&bull;&nbsp; {theme_name}",
                    badge_style,
                )
            )

            story.append(Paragraph(slide.title, title_style))
            story.append(Spacer(1, 6))

            for bullet in slide.bullet_points:
                story.append(Paragraph(f"&bull;&nbsp;&nbsp;{bullet}", bullet_style))

            if slide.diagram_code and slide.diagram_code.strip():
                story.append(Spacer(1, 10))
                diagram_style = ParagraphStyle(
                    "DiagramCode",
                    parent=styles["Code"],
                    fontName="Courier",
                    fontSize=9,
                    leading=12,
                    textColor=colors.HexColor("#475569"),
                    backColor=colors.HexColor("#F8FAFC"),
                    borderColor=colors.HexColor("#E2E8F0"),
                    borderWidth=1,
                    borderPadding=8,
                    spaceAfter=10,
                )
                formatted_diagram = slide.diagram_code.replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br/>")
                story.append(
                    Paragraph(
                        f"<b>Diagram (Mermaid):</b><br/>{formatted_diagram}",
                        diagram_style,
                    )
                )

            if index < len(slides) - 1:
                story.append(PageBreak())

        doc.build(story)

        pdf_value = buffer.getvalue()
        buffer.close()

        response = HttpResponse(pdf_value, content_type="application/pdf")
        response["Content-Disposition"] = (
            f'attachment; filename="fafanua_presentation_{presentation.id}.pdf"'
        )
        return response


class PresentationPPTXExportView(APIView):
    """
    Exports a presentation as a downloadable PowerPoint (.pptx) file.
    GET /api/history/<uuid:pk>/export/pptx/
    """

    @swagger_auto_schema(
        operation_summary="Export presentation as PowerPoint (.pptx)",
        operation_description="Generates a downloadable PowerPoint presentation (.pptx) file with theme styling.",
        responses={
            200: openapi.Response(
                description="Binary PPTX file stream.",
                schema=openapi.Schema(type=openapi.TYPE_FILE),
            ),
            404: "Presentation not found.",
        },
    )
    def get(self, request: Request, pk: str) -> HttpResponse:
        presentation = get_object_or_404(Presentation, pk=pk)
        buffer = PPTXGenerator().generate_presentation(presentation)

        response = HttpResponse(
            buffer.getvalue(),
            content_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        )
        response["Content-Disposition"] = (
            f'attachment; filename="Fafanua_Presentation_{presentation.id}.pptx"'
        )
        return response
