"""
storyteller/views.py

HTTP layer for the Fafanua slide generation API.

This module contains only HTTP-level concerns: request parsing, input
validation, error translation, and response serialisation. All business
logic and external-API communication lives in services.py.
"""

import logging

from django.db import transaction
from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema
from rest_framework import status
from rest_framework.generics import get_object_or_404
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Presentation, Slide
from .serializers import PresentationSerializer
from .services import WatsonxService

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# OpenAPI schema definitions (reused across decorator and response docs)
# ---------------------------------------------------------------------------

_slide_schema = openapi.Schema(
    type=openapi.TYPE_OBJECT,
    description="A single presentation slide generated by the Granite model.",
    required=["title", "bullet_points", "theme_variant"],
    properties={
        "title": openapi.Schema(
            type=openapi.TYPE_STRING,
            description="Concise, punchy slide title.",
            example="Decoupled Architecture Overview",
        ),
        "bullet_points": openapi.Schema(
            type=openapi.TYPE_ARRAY,
            description="3–5 audience-friendly bullet points.",
            items=openapi.Schema(
                type=openapi.TYPE_STRING,
                example="The React frontend communicates with Django via a REST API.",
            ),
        ),
        "theme_variant": openapi.Schema(
            type=openapi.TYPE_STRING,
            description='Visual theme. Must be one of: "warm", "bold", or "clean".',
            enum=["warm", "bold", "clean"],
            example="bold",
        ),
    },
)

_request_schema = openapi.Schema(
    type=openapi.TYPE_OBJECT,
    required=["technical_content"],
    properties={
        "technical_content": openapi.Schema(
            type=openapi.TYPE_STRING,
            description=(
                "Dense technical text to transform — architecture docs, "
                "code snippets, system logs, or API specifications."
            ),
            example="Our system uses a React frontend with a Django REST API backend...",
        )
    },
)

_presentation_response_schema = openapi.Schema(
    type=openapi.TYPE_OBJECT,
    description="A persisted presentation with nested slides.",
    properties={
        "id": openapi.Schema(
            type=openapi.TYPE_STRING,
            format="uuid",
            description="Unique presentation identifier.",
        ),
        "original_text": openapi.Schema(
            type=openapi.TYPE_STRING,
            description="The original technical content submitted.",
        ),
        "slides": openapi.Schema(
            type=openapi.TYPE_ARRAY,
            items=_slide_schema,
            description="Ordered list of generated slides.",
        ),
        "created_at": openapi.Schema(
            type=openapi.TYPE_STRING,
            format="date-time",
            description="ISO-8601 creation timestamp.",
        ),
        "updated_at": openapi.Schema(
            type=openapi.TYPE_STRING,
            format="date-time",
            description="ISO-8601 last-updated timestamp.",
        ),
    },
)


class GeneratePresentationView(APIView):
    """POST /api/generate/ — converts technical text into a JSON slide deck.

    Accepts a JSON body containing ``technical_content``, delegates the heavy
    lifting to :class:`~storyteller.services.WatsonxService`, persists the
    result as a :class:`~storyteller.models.Presentation` with linked
    :class:`~storyteller.models.Slide` records, and returns the serialised
    presentation.

    HTTP Methods:
        POST

    Request Body (JSON)::

        {
            "technical_content": "<dense technical text, code, or architecture docs>"
        }

    Successful Response — 200 OK::

        {
            "id": "<uuid>",
            "original_text": "...",
            "slides": [ { "title": "...", ... }, ... ],
            "created_at": "...",
            "updated_at": "..."
        }

    Error Responses:
        - **400 Bad Request** — ``technical_content`` is missing or blank.
        - **502 Bad Gateway** — watsonx.ai API returned an upstream error.
        - **500 Internal Server Error** — Unexpected failure or unparseable model response.
    """

    @swagger_auto_schema(
        operation_id="generate_presentation",
        operation_summary="Generate a slide deck from technical content",
        operation_description=(
            "Accepts dense technical text and returns a persisted presentation "
            "object containing a structured JSON array of slides. Each slide is "
            "generated by the IBM Granite model (`ibm/granite-3-3-8b-instruct`) "
            "via a zero-shot prompt and contains a title, bullet points, and a "
            "theme variant. The presentation and its slides are saved to the "
            "database for later retrieval via the history endpoints."
        ),
        request_body=_request_schema,
        responses={
            200: openapi.Response(
                description="Presentation generated and persisted successfully.",
                schema=_presentation_response_schema,
            ),
            400: openapi.Response(
                description="Bad Request — `technical_content` is missing or blank.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(
                            type=openapi.TYPE_STRING,
                            example="'technical_content' is required and must not be blank.",
                        )
                    },
                ),
            ),
            502: openapi.Response(
                description="Bad Gateway — IBM watsonx.ai API returned an upstream error.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(type=openapi.TYPE_STRING),
                        "upstream_error": openapi.Schema(type=openapi.TYPE_STRING),
                    },
                ),
            ),
            500: openapi.Response(
                description="Internal Server Error — server misconfiguration or unparseable model output.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(type=openapi.TYPE_STRING),
                        "parse_error": openapi.Schema(type=openapi.TYPE_STRING),
                    },
                ),
            ),
        },
        tags=["Slide Generation"],
    )
    def post(self, request: Request, *args, **kwargs) -> Response:
        """Handle POST requests by generating a slide deck via IBM watsonx.ai.

        Args:
            request: The DRF request object. Expects a JSON body with the key
                ``technical_content``.
            *args: Additional positional arguments (passed through, unused).
            **kwargs: Additional keyword arguments (passed through, unused).

        Returns:
            A :class:`rest_framework.response.Response` containing either:

            - A serialised ``Presentation`` dict on success (HTTP 200).
            - An error dict with a ``detail`` key on failure (HTTP 400/500/502).
        """
        # ------------------------------------------------------------------ #
        # 1. Input validation
        # ------------------------------------------------------------------ #
        technical_content: str = request.data.get("technical_content", "").strip()

        if not technical_content:
            return Response(
                {
                    "detail": (
                        "'technical_content' is required and must not be blank. "
                        "Paste your technical text, code snippet, or architecture "
                        "notes into this field."
                    )
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

        # ------------------------------------------------------------------ #
        # 2. Delegate to the service layer
        # ------------------------------------------------------------------ #
        try:
            service = WatsonxService()
            slides = service.generate_slides(technical_content)

        except EnvironmentError as exc:
            # Misconfigured server — watsonx credentials not set in .env
            logger.error("WatsonxService configuration error: %s", exc)
            return Response(
                {"detail": f"Server configuration error: {exc}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        except RuntimeError as exc:
            # watsonx.ai upstream API failure (network, auth, quota, etc.)
            logger.error("watsonx.ai upstream error: %s", exc)
            return Response(
                {
                    "detail": (
                        "The AI service returned an error. "
                        "Please try again in a moment."
                    ),
                    "upstream_error": str(exc),
                },
                status=status.HTTP_502_BAD_GATEWAY,
            )

        except ValueError as exc:
            # Model returned non-parseable output
            logger.error("JSON parse error from model response: %s", exc)
            return Response(
                {
                    "detail": (
                        "The AI model returned an unexpected response format. "
                        "This is likely transient — please retry your request."
                    ),
                    "parse_error": str(exc),
                },
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        # ------------------------------------------------------------------ #
        # 3. Persist the presentation and slides
        # ------------------------------------------------------------------ #
        try:
            with transaction.atomic():
                presentation = Presentation.objects.create(
                    original_text=technical_content,
                )

                slide_objects = [
                    Slide(
                        presentation=presentation,
                        slide_order=idx,
                        title=slide_data.get("title", ""),
                        bullet_points=slide_data.get("bullet_points", []),
                        theme_variant=slide_data.get("theme_variant", "clean"),
                    )
                    for idx, slide_data in enumerate(slides)
                ]
                Slide.objects.bulk_create(slide_objects)

        except Exception as exc:
            logger.exception(
                "Failed to persist presentation to database: %s", exc
            )
            # Even though DB write failed, the slides were generated
            # successfully. Return them with an error flag so the frontend
            # can still display the content.
            return Response(
                {
                    "detail": (
                        "Slides were generated successfully, but could not be "
                        "saved to the database. They will not appear in your "
                        "history."
                    ),
                    "slides": slides,
                },
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        # ------------------------------------------------------------------ #
        # 4. Return serialised presentation
        # ------------------------------------------------------------------ #
        serializer = PresentationSerializer(presentation)
        logger.info(
            "Successfully generated and persisted presentation %s with %d slides.",
            presentation.id,
            len(slides),
        )
        return Response(serializer.data, status=status.HTTP_200_OK)


# ---------------------------------------------------------------------------
# History endpoints
# ---------------------------------------------------------------------------


class PresentationListView(APIView):
    """GET /api/history/ — returns all presentations ordered by newest first.

    HTTP Methods:
        GET

    Successful Response — 200 OK::

        [
            {
                "id": "<uuid>",
                "original_text": "...",
                "slides": [...],
                "created_at": "...",
                "updated_at": "..."
            },
            ...
        ]
    """

    @swagger_auto_schema(
        operation_id="list_presentations",
        operation_summary="List all generated presentations",
        operation_description=(
            "Returns a chronologically ordered list (newest first) of all "
            "persisted presentations, each including its nested slides."
        ),
        responses={
            200: openapi.Response(
                description="List of presentations retrieved successfully.",
                schema=openapi.Schema(
                    type=openapi.TYPE_ARRAY,
                    items=_presentation_response_schema,
                ),
            ),
        },
        tags=["Presentation History"],
    )
    def get(self, request: Request) -> Response:
        """Return all presentations ordered by most recent first.

        Args:
            request: The DRF request object.

        Returns:
            A list of serialised Presentation objects.
        """
        presentations = Presentation.objects.prefetch_related("slides").all()
        serializer = PresentationSerializer(presentations, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


class PresentationDetailView(APIView):
    """GET /api/history/<uuid:pk>/ — returns a single presentation by its UUID.

    HTTP Methods:
        GET

    Successful Response — 200 OK::

        {
            "id": "<uuid>",
            "original_text": "...",
            "slides": [...],
            "created_at": "...",
            "updated_at": "..."
        }

    Error Responses:
        - **404 Not Found** — No presentation with the given UUID exists.
    """

    @swagger_auto_schema(
        operation_id="retrieve_presentation",
        operation_summary="Retrieve a single presentation by UUID",
        operation_description=(
            "Returns a single presentation identified by its UUID, including "
            "all nested slides. Returns 404 if the UUID does not match any "
            "existing presentation."
        ),
        manual_parameters=[
            openapi.Parameter(
                "pk",
                openapi.IN_PATH,
                description="UUID of the presentation to retrieve.",
                type=openapi.TYPE_STRING,
                format="uuid",
                required=True,
            ),
        ],
        responses={
            200: openapi.Response(
                description="Presentation retrieved successfully.",
                schema=_presentation_response_schema,
            ),
            404: openapi.Response(
                description="Not Found — no presentation matches the given UUID.",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "detail": openapi.Schema(
                            type=openapi.TYPE_STRING,
                            example="Not found.",
                        )
                    },
                ),
            ),
        },
        tags=["Presentation History"],
    )
    def get(self, request: Request, pk) -> Response:
        """Return a single presentation by its primary key.

        Args:
            request: The DRF request object.
            pk: The UUID of the presentation to retrieve.

        Returns:
            A serialised Presentation object, or a 404 error response.
        """
        presentation = get_object_or_404(
            Presentation.objects.prefetch_related("slides"),
            pk=pk,
        )
        serializer = PresentationSerializer(presentation)
        return Response(serializer.data, status=status.HTTP_200_OK)
